### ISSUE TITLE
?mongod

### ISSUE THREAD

**Issue by jb08** [scotch-io/node-todo#26]
```
ch-nb-1614:node-todo jbrown$ node server.js
App listening on port 8080

/Users/jbrown/Documents/Repos/node-todo/node_modules/mongodb/lib/server.js:265
        process.nextTick(function() { throw err; })
                                      ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at null.<anonymous> (/Users/jbrown/Documents/Repos/node-todo/node_modules/mongodb-core/lib/topologies/server.js:325:35)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/jbrown/Documents/Repos/node-todo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/Users/jbrown/Documents/Repos/node-todo/node_modules/mongodb-core/lib/connection/connection.js:173:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by Sarasranglt** [comment]
Have you been able to find a fix ?

**Comment by jb08** [comment]
thanks @Sarasranglt ; that helped as did changing line 12 of server.js:
`mongoose.connect(database.localUrl);`
