### ISSUE TITLE
Anyone knows something about this error? Thanks!

### ISSUE THREAD

**Issue by pavazmo** [scotch-io/node-todo#28]
~/projects/tutorials/yournewapp $ node server.js               
App listening on port 8080
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connection closed
    at null.<anonymous> (/home/pat/projects/tutorials/yournewapp/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:592:24)
    at emitNone (events.js:67:13)
    at emit (events.js:166:7)
    at null.<anonymous> (/home/pat/projects/tutorials/yournewapp/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:155:15)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/home/pat/projects/tutorials/yournewapp/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:494:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:487:12)

**Comment by nitin-tiwari** [comment]
I get the same error, so any comments from Author will be useful.

**Comment by pavazmo** [comment]
I thought I solved it in the past. I think we got this error because there was something running in port 8080. Try clossing other node's service running and tell me :) .

`ps aux | grep node`

![seleccion_004](https://user-images.githubusercontent.com/23095875/34204414-d189befc-e57e-11e7-9a94-354d5a189e1b.png)

**Comment by uzzal2k5** [comment]
This error shows only when , you run server.js with "`node server.js` " command, then the applicationn start listenning 8080 port as it is indicates into code, after that the server try to connect database (mongodb), anyhow it **can't connect to the database**. 

if you use 

> hostname

 rather than IP address , hostname can't resolve.  or   or IP port can't reach. 
If you use docker container to run the application, then use `docker-compose`. this will help you to resolve DNS or otherwise USE direct IP address.  To test database connection try following instruction -

install mongodb driver to connect using IP , PORT or hostname , post  which on you use.
Suppose , If you use Ubuntu then

> `apt-get install mongodb`
> 
> `mongo -h hostname/IP -p 27017` 
> 

You will be able to connect mongodb, If you have user name and password then use
`mongo -u usename -p -h hostname -p 27017`

Hope this will help you to resolve this issue
